// autogenerated
namespace InvoiceXpress.Map;

/// <summary />
internal partial class IXCountry
{
    /// <summary />
    internal static readonly List<IXCountry> Map = new List<IXCountry>()
    {
        new IXCountry( "PT", "Portugal" ),
    };
}
