// autogenerated
using InvoiceXpress.Json;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace InvoiceXpress;

/// <summary />
/// <remarks>
/// List of countries as per: https://invoicexpress.com/api-v2/documentation/appendix
/// </remarks>
[JsonConverter( typeof( EnumConverter ) )]
public enum Country
{
    /// <summary>
    /// AD, Andorra
    /// </summary>
    [EnumMember( Value = "Andorra" )]
    AD,

    /// <summary>
    /// AE, United Arab Emirates
    /// </summary>
    [EnumMember( Value = "United Arab Emirates" )]
    AE,

    /// <summary>
    /// AF, Afghanistan
    /// </summary>
    [EnumMember( Value = "Afghanistan" )]
    AF,

    /// <summary>
    /// AG, Antigua and Barbuda
    /// </summary>
    [EnumMember( Value = "Antigua and Barbuda" )]
    AG,

    /// <summary>
    /// AI, Anguilla
    /// </summary>
    [EnumMember( Value = "Anguilla" )]
    AI,

    /// <summary>
    /// AL, Albania
    /// </summary>
    [EnumMember( Value = "Albania" )]
    AL,

    /// <summary>
    /// AM, Armenia
    /// </summary>
    [EnumMember( Value = "Armenia" )]
    AM,

    /// <summary>
    /// AO, Angola
    /// </summary>
    [EnumMember( Value = "Angola" )]
    AO,

    /// <summary>
    /// AR, Argentina
    /// </summary>
    [EnumMember( Value = "Argentina" )]
    AR,

    /// <summary>
    /// AS, American Samoa
    /// </summary>
    [EnumMember( Value = "American Samoa" )]
    AS,

    /// <summary>
    /// AT, Austria
    /// </summary>
    [EnumMember( Value = "Austria" )]
    AT,

    /// <summary>
    /// AU, Australia
    /// </summary>
    [EnumMember( Value = "Australia" )]
    AU,

    /// <summary>
    /// AW, Aruba
    /// </summary>
    [EnumMember( Value = "Aruba" )]
    AW,

    /// <summary>
    /// AZ, Azerbaijan
    /// </summary>
    [EnumMember( Value = "Azerbaijan" )]
    AZ,

    /// <summary>
    /// BA, Bosnia and Herzegovina
    /// </summary>
    [EnumMember( Value = "Bosnia-Herzegovina" )]
    BA,

    /// <summary>
    /// BB, Barbados
    /// </summary>
    [EnumMember( Value = "Barbados" )]
    BB,

    /// <summary>
    /// BD, Bangladesh
    /// </summary>
    [EnumMember( Value = "Bangladesh" )]
    BD,

    /// <summary>
    /// BE, Belgium
    /// </summary>
    [EnumMember( Value = "Belgium" )]
    BE,

    /// <summary>
    /// BF, Burkina Faso
    /// </summary>
    [EnumMember( Value = "Burkina Faso" )]
    BF,

    /// <summary>
    /// BG, Bulgaria
    /// </summary>
    [EnumMember( Value = "Bulgaria" )]
    BG,

    /// <summary>
    /// BH, Bahrain
    /// </summary>
    [EnumMember( Value = "Bahrain" )]
    BH,

    /// <summary>
    /// BI, Burundi
    /// </summary>
    [EnumMember( Value = "Burundi" )]
    BI,

    /// <summary>
    /// BJ, Benin
    /// </summary>
    [EnumMember( Value = "Benin" )]
    BJ,

    /// <summary>
    /// BM, Bermuda
    /// </summary>
    [EnumMember( Value = "Bermuda" )]
    BM,

    /// <summary>
    /// BN, Brunei
    /// </summary>
    [EnumMember( Value = "Brunei" )]
    BN,

    /// <summary>
    /// BO, Bolivia
    /// </summary>
    [EnumMember( Value = "Bolivia" )]
    BO,

    /// <summary>
    /// BR, Brazil
    /// </summary>
    [EnumMember( Value = "Brazil" )]
    BR,

    /// <summary>
    /// BS, Bahamas
    /// </summary>
    [EnumMember( Value = "Bahamas" )]
    BS,

    /// <summary>
    /// BT, Bhutan
    /// </summary>
    [EnumMember( Value = "Bhutan" )]
    BT,

    /// <summary>
    /// BW, Botswana
    /// </summary>
    [EnumMember( Value = "Botswana" )]
    BW,

    /// <summary>
    /// BY, Belarus
    /// </summary>
    [EnumMember( Value = "Belarus" )]
    BY,

    /// <summary>
    /// BZ, Belize
    /// </summary>
    [EnumMember( Value = "Belize" )]
    BZ,

    /// <summary>
    /// CA, Canada
    /// </summary>
    [EnumMember( Value = "Canada" )]
    CA,

    /// <summary>
    /// CC, Cocos (Keeling) Islands
    /// </summary>
    [EnumMember( Value = "Cocos (Keeling) Islands" )]
    CC,

    /// <summary>
    /// CD, DR Congo
    /// </summary>
    [EnumMember( Value = "Congo" )]
    CD,

    /// <summary>
    /// CF, Central African Republic
    /// </summary>
    [EnumMember( Value = "Central African Republic" )]
    CF,

    /// <summary>
    /// CH, Switzerland
    /// </summary>
    [EnumMember( Value = "Switzerland" )]
    CH,

    /// <summary>
    /// CI, Ivory Coast
    /// </summary>
    [EnumMember( Value = "Ivory Coast" )]
    CI,

    /// <summary>
    /// CK, Cook Islands
    /// </summary>
    [EnumMember( Value = "Cook Islands" )]
    CK,

    /// <summary>
    /// CL, Chile
    /// </summary>
    [EnumMember( Value = "Chile" )]
    CL,

    /// <summary>
    /// CM, Cameroon
    /// </summary>
    [EnumMember( Value = "Cameroon" )]
    CM,

    /// <summary>
    /// CN, China
    /// </summary>
    [EnumMember( Value = "China" )]
    CN,

    /// <summary>
    /// CO, Colombia
    /// </summary>
    [EnumMember( Value = "Colombia" )]
    CO,

    /// <summary>
    /// CR, Costa Rica
    /// </summary>
    [EnumMember( Value = "Costa Rica" )]
    CR,

    /// <summary>
    /// CU, Cuba
    /// </summary>
    [EnumMember( Value = "Cuba" )]
    CU,

    /// <summary>
    /// CV, Cape Verde
    /// </summary>
    [EnumMember( Value = "Cape Verde" )]
    CV,

    /// <summary>
    /// CW, Curaçao
    /// </summary>
    [EnumMember( Value = "Curaçao" )]
    CW,

    /// <summary>
    /// CX, Christmas Island
    /// </summary>
    [EnumMember( Value = "Christmas Island" )]
    CX,

    /// <summary>
    /// CY, Cyprus
    /// </summary>
    [EnumMember( Value = "Cyprus" )]
    CY,

    /// <summary>
    /// CZ, Czechia
    /// </summary>
    [EnumMember( Value = "Czech Republic" )]
    CZ,

    /// <summary>
    /// DE, Germany
    /// </summary>
    [EnumMember( Value = "Germany" )]
    DE,

    /// <summary>
    /// DJ, Djibouti
    /// </summary>
    [EnumMember( Value = "Djibouti" )]
    DJ,

    /// <summary>
    /// DK, Denmark
    /// </summary>
    [EnumMember( Value = "Denmark" )]
    DK,

    /// <summary>
    /// DM, Dominica
    /// </summary>
    [EnumMember( Value = "Dominica" )]
    DM,

    /// <summary>
    /// DO, Dominican Republic
    /// </summary>
    [EnumMember( Value = "Dominican Republic" )]
    DO,

    /// <summary>
    /// DZ, Algeria
    /// </summary>
    [EnumMember( Value = "Algeria" )]
    DZ,

    /// <summary>
    /// EC, Ecuador
    /// </summary>
    [EnumMember( Value = "Ecuador" )]
    EC,

    /// <summary>
    /// EE, Estonia
    /// </summary>
    [EnumMember( Value = "Estonia" )]
    EE,

    /// <summary>
    /// EG, Egypt
    /// </summary>
    [EnumMember( Value = "Egypt" )]
    EG,

    /// <summary>
    /// EH, Western Sahara
    /// </summary>
    [EnumMember( Value = "Western Sahara" )]
    EH,

    /// <summary>
    /// ER, Eritrea
    /// </summary>
    [EnumMember( Value = "Eritrea" )]
    ER,

    /// <summary>
    /// ES, Spain
    /// </summary>
    [EnumMember( Value = "Spain" )]
    ES,

    /// <summary>
    /// ET, Ethiopia
    /// </summary>
    [EnumMember( Value = "Ethiopia" )]
    ET,

    /// <summary>
    /// FI, Finland
    /// </summary>
    [EnumMember( Value = "Finland" )]
    FI,

    /// <summary>
    /// FJ, Fiji
    /// </summary>
    [EnumMember( Value = "Fiji" )]
    FJ,

    /// <summary>
    /// FK, Falkland Islands
    /// </summary>
    [EnumMember( Value = "Falkland Islands" )]
    FK,

    /// <summary>
    /// FM, Micronesia
    /// </summary>
    [EnumMember( Value = "Micronesia" )]
    FM,

    /// <summary>
    /// FO, Faroe Islands
    /// </summary>
    [EnumMember( Value = "Faeroe Islands (Føroyar)" )]
    FO,

    /// <summary>
    /// FR, France
    /// </summary>
    [EnumMember( Value = "France" )]
    FR,

    /// <summary>
    /// GA, Gabon
    /// </summary>
    [EnumMember( Value = "Gabon" )]
    GA,

    /// <summary>
    /// GB, United Kingdom
    /// </summary>
    [EnumMember( Value = "UK" )]
    GB,

    /// <summary>
    /// GD, Grenada
    /// </summary>
    [EnumMember( Value = "Grenada" )]
    GD,

    /// <summary>
    /// GE, Georgia
    /// </summary>
    [EnumMember( Value = "Georgia" )]
    GE,

    /// <summary>
    /// GF, French Guiana
    /// </summary>
    [EnumMember( Value = "French Guiana" )]
    GF,

    /// <summary>
    /// GG, Guernsey
    /// </summary>
    [EnumMember( Value = "Guernsey" )]
    GG,

    /// <summary>
    /// GH, Ghana
    /// </summary>
    [EnumMember( Value = "Ghana" )]
    GH,

    /// <summary>
    /// GI, Gibraltar
    /// </summary>
    [EnumMember( Value = "Gibraltar" )]
    GI,

    /// <summary>
    /// GL, Greenland
    /// </summary>
    [EnumMember( Value = "Greenland" )]
    GL,

    /// <summary>
    /// GM, Gambia
    /// </summary>
    [EnumMember( Value = "Gambia" )]
    GM,

    /// <summary>
    /// GN, Guinea
    /// </summary>
    [EnumMember( Value = "Guinea" )]
    GN,

    /// <summary>
    /// GP, Guadeloupe
    /// </summary>
    [EnumMember( Value = "Guadeloupe" )]
    GP,

    /// <summary>
    /// GQ, Equatorial Guinea
    /// </summary>
    [EnumMember( Value = "Equatorial Guinea" )]
    GQ,

    /// <summary>
    /// GR, Greece
    /// </summary>
    [EnumMember( Value = "Greece" )]
    GR,

    /// <summary>
    /// GT, Guatemala
    /// </summary>
    [EnumMember( Value = "Guatemala" )]
    GT,

    /// <summary>
    /// GU, Guam
    /// </summary>
    [EnumMember( Value = "Guam" )]
    GU,

    /// <summary>
    /// GW, Guinea-Bissau
    /// </summary>
    [EnumMember( Value = "Guinea-Bissau" )]
    GW,

    /// <summary>
    /// GY, Guyana
    /// </summary>
    [EnumMember( Value = "Guyana" )]
    GY,

    /// <summary>
    /// HK, Hong Kong
    /// </summary>
    [EnumMember( Value = "Hong Kong" )]
    HK,

    /// <summary>
    /// HN, Honduras
    /// </summary>
    [EnumMember( Value = "Honduras" )]
    HN,

    /// <summary>
    /// HR, Croatia
    /// </summary>
    [EnumMember( Value = "Croatia" )]
    HR,

    /// <summary>
    /// HT, Haiti
    /// </summary>
    [EnumMember( Value = "Haiti" )]
    HT,

    /// <summary>
    /// HU, Hungary
    /// </summary>
    [EnumMember( Value = "Hungary" )]
    HU,

    /// <summary>
    /// ID, Indonesia
    /// </summary>
    [EnumMember( Value = "Indonesia" )]
    ID,

    /// <summary>
    /// IE, Ireland
    /// </summary>
    [EnumMember( Value = "Ireland" )]
    IE,

    /// <summary>
    /// IL, Israel
    /// </summary>
    [EnumMember( Value = "Israel" )]
    IL,

    /// <summary>
    /// IM, Isle of Man
    /// </summary>
    [EnumMember( Value = "Isle of Man" )]
    IM,

    /// <summary>
    /// IN, India
    /// </summary>
    [EnumMember( Value = "India" )]
    IN,

    /// <summary>
    /// IO, British Indian Ocean Territory
    /// </summary>
    [EnumMember( Value = "British Indian Ocean Territory" )]
    IO,

    /// <summary>
    /// IQ, Iraq
    /// </summary>
    [EnumMember( Value = "Iraq" )]
    IQ,

    /// <summary>
    /// IR, Iran
    /// </summary>
    [EnumMember( Value = "Iran" )]
    IR,

    /// <summary>
    /// IS, Iceland
    /// </summary>
    [EnumMember( Value = "Iceland" )]
    IS,

    /// <summary>
    /// IT, Italy
    /// </summary>
    [EnumMember( Value = "Italy" )]
    IT,

    /// <summary>
    /// JE, Jersey
    /// </summary>
    [EnumMember( Value = "Jersey" )]
    JE,

    /// <summary>
    /// JM, Jamaica
    /// </summary>
    [EnumMember( Value = "Jamaica" )]
    JM,

    /// <summary>
    /// JO, Jordan
    /// </summary>
    [EnumMember( Value = "Jordan" )]
    JO,

    /// <summary>
    /// JP, Japan
    /// </summary>
    [EnumMember( Value = "Japan" )]
    JP,

    /// <summary>
    /// KE, Kenya
    /// </summary>
    [EnumMember( Value = "Kenya" )]
    KE,

    /// <summary>
    /// KG, Kyrgyzstan
    /// </summary>
    [EnumMember( Value = "Kyrgyzstan" )]
    KG,

    /// <summary>
    /// KH, Cambodia
    /// </summary>
    [EnumMember( Value = "Cambodia" )]
    KH,

    /// <summary>
    /// KI, Kiribati
    /// </summary>
    [EnumMember( Value = "Kiribati" )]
    KI,

    /// <summary>
    /// KM, Comoros
    /// </summary>
    [EnumMember( Value = "Comoros" )]
    KM,

    /// <summary>
    /// KN, Saint Kitts and Nevis
    /// </summary>
    [EnumMember( Value = "St. Kitts and Nevis" )]
    KN,

    /// <summary>
    /// KP, North Korea
    /// </summary>
    [EnumMember( Value = "Korea, North" )]
    KP,

    /// <summary>
    /// KR, South Korea
    /// </summary>
    [EnumMember( Value = "Korea, South" )]
    KR,

    /// <summary>
    /// KW, Kuwait
    /// </summary>
    [EnumMember( Value = "Kuwait" )]
    KW,

    /// <summary>
    /// KY, Cayman Islands
    /// </summary>
    [EnumMember( Value = "Cayman Islands" )]
    KY,

    /// <summary>
    /// KZ, Kazakhstan
    /// </summary>
    [EnumMember( Value = "Kazakhstan" )]
    KZ,

    /// <summary>
    /// LA, Laos
    /// </summary>
    [EnumMember( Value = "Laos" )]
    LA,

    /// <summary>
    /// LB, Lebanon
    /// </summary>
    [EnumMember( Value = "Lebanon" )]
    LB,

    /// <summary>
    /// LC, Saint Lucia
    /// </summary>
    [EnumMember( Value = "St. Lucia" )]
    LC,

    /// <summary>
    /// LI, Liechtenstein
    /// </summary>
    [EnumMember( Value = "Liechtenstein" )]
    LI,

    /// <summary>
    /// LK, Sri Lanka
    /// </summary>
    [EnumMember( Value = "Sri Lanka" )]
    LK,

    /// <summary>
    /// LR, Liberia
    /// </summary>
    [EnumMember( Value = "Liberia" )]
    LR,

    /// <summary>
    /// LS, Lesotho
    /// </summary>
    [EnumMember( Value = "Lesotho" )]
    LS,

    /// <summary>
    /// LT, Lithuania
    /// </summary>
    [EnumMember( Value = "Lithuania" )]
    LT,

    /// <summary>
    /// LU, Luxembourg
    /// </summary>
    [EnumMember( Value = "Luxembourg" )]
    LU,

    /// <summary>
    /// LV, Latvia
    /// </summary>
    [EnumMember( Value = "Latvia" )]
    LV,

    /// <summary>
    /// LY, Libya
    /// </summary>
    [EnumMember( Value = "Libya" )]
    LY,

    /// <summary>
    /// MA, Morocco
    /// </summary>
    [EnumMember( Value = "Morocco" )]
    MA,

    /// <summary>
    /// MC, Monaco
    /// </summary>
    [EnumMember( Value = "Monaco" )]
    MC,

    /// <summary>
    /// MD, Moldova
    /// </summary>
    [EnumMember( Value = "Moldova" )]
    MD,

    /// <summary>
    /// ME, Montenegro
    /// </summary>
    [EnumMember( Value = "Montenegro" )]
    ME,

    /// <summary>
    /// MG, Madagascar
    /// </summary>
    [EnumMember( Value = "Madagascar" )]
    MG,

    /// <summary>
    /// MH, Marshall Islands
    /// </summary>
    [EnumMember( Value = "Marshall Islands" )]
    MH,

    /// <summary>
    /// MK, North Macedonia
    /// </summary>
    [EnumMember( Value = "Macedonia (Former Yug. Rep.)" )]
    MK,

    /// <summary>
    /// ML, Mali
    /// </summary>
    [EnumMember( Value = "Mali" )]
    ML,

    /// <summary>
    /// MM, Myanmar
    /// </summary>
    [EnumMember( Value = "Myanmar" )]
    MM,

    /// <summary>
    /// MN, Mongolia
    /// </summary>
    [EnumMember( Value = "Mongolia" )]
    MN,

    /// <summary>
    /// MO, Macau
    /// </summary>
    [EnumMember( Value = "Macau" )]
    MO,

    /// <summary>
    /// MP, Northern Mariana Islands
    /// </summary>
    [EnumMember( Value = "Northern Mariana Islands" )]
    MP,

    /// <summary>
    /// MQ, Martinique
    /// </summary>
    [EnumMember( Value = "Martinique" )]
    MQ,

    /// <summary>
    /// MR, Mauritania
    /// </summary>
    [EnumMember( Value = "Mauritania" )]
    MR,

    /// <summary>
    /// MS, Montserrat
    /// </summary>
    [EnumMember( Value = "Montserrat" )]
    MS,

    /// <summary>
    /// MT, Malta
    /// </summary>
    [EnumMember( Value = "Malta" )]
    MT,

    /// <summary>
    /// MU, Mauritius
    /// </summary>
    [EnumMember( Value = "Mauritius" )]
    MU,

    /// <summary>
    /// MV, Maldives
    /// </summary>
    [EnumMember( Value = "Maldives" )]
    MV,

    /// <summary>
    /// MW, Malawi
    /// </summary>
    [EnumMember( Value = "Malawi" )]
    MW,

    /// <summary>
    /// MX, Mexico
    /// </summary>
    [EnumMember( Value = "Mexico" )]
    MX,

    /// <summary>
    /// MY, Malaysia
    /// </summary>
    [EnumMember( Value = "Malaysia" )]
    MY,

    /// <summary>
    /// MZ, Mozambique
    /// </summary>
    [EnumMember( Value = "Mozambique" )]
    MZ,

    /// <summary>
    /// NA, Namibia
    /// </summary>
    [EnumMember( Value = "Namibia" )]
    NA,

    /// <summary>
    /// NC, New Caledonia
    /// </summary>
    [EnumMember( Value = "New Caledonia" )]
    NC,

    /// <summary>
    /// NE, Niger
    /// </summary>
    [EnumMember( Value = "Niger" )]
    NE,

    /// <summary>
    /// NF, Norfolk Island
    /// </summary>
    [EnumMember( Value = "Norfolk Island" )]
    NF,

    /// <summary>
    /// NG, Nigeria
    /// </summary>
    [EnumMember( Value = "Nigeria" )]
    NG,

    /// <summary>
    /// NI, Nicaragua
    /// </summary>
    [EnumMember( Value = "Nicaragua" )]
    NI,

    /// <summary>
    /// NL, Netherlands
    /// </summary>
    [EnumMember( Value = "Netherlands" )]
    NL,

    /// <summary>
    /// NO, Norway
    /// </summary>
    [EnumMember( Value = "Norway" )]
    NO,

    /// <summary>
    /// NP, Nepal
    /// </summary>
    [EnumMember( Value = "Nepal" )]
    NP,

    /// <summary>
    /// NR, Nauru
    /// </summary>
    [EnumMember( Value = "Nauru" )]
    NR,

    /// <summary>
    /// NU, Niue
    /// </summary>
    [EnumMember( Value = "Niue" )]
    NU,

    /// <summary>
    /// NZ, New Zealand
    /// </summary>
    [EnumMember( Value = "New Zealand" )]
    NZ,

    /// <summary>
    /// OM, Oman
    /// </summary>
    [EnumMember( Value = "Oman" )]
    OM,

    /// <summary>
    /// PA, Panama
    /// </summary>
    [EnumMember( Value = "Panama" )]
    PA,

    /// <summary>
    /// PE, Peru
    /// </summary>
    [EnumMember( Value = "Peru" )]
    PE,

    /// <summary>
    /// PF, French Polynesia
    /// </summary>
    [EnumMember( Value = "French Polynesia" )]
    PF,

    /// <summary>
    /// PG, Papua New Guinea
    /// </summary>
    [EnumMember( Value = "Papua New Guinea" )]
    PG,

    /// <summary>
    /// PH, Philippines
    /// </summary>
    [EnumMember( Value = "Philippines" )]
    PH,

    /// <summary>
    /// PK, Pakistan
    /// </summary>
    [EnumMember( Value = "Pakistan" )]
    PK,

    /// <summary>
    /// PL, Poland
    /// </summary>
    [EnumMember( Value = "Poland" )]
    PL,

    /// <summary>
    /// PN, Pitcairn Islands
    /// </summary>
    [EnumMember( Value = "Pitcairn Island" )]
    PN,

    /// <summary>
    /// PR, Puerto Rico
    /// </summary>
    [EnumMember( Value = "Puerto Rico" )]
    PR,

    /// <summary>
    /// PS, Palestine
    /// </summary>
    [EnumMember( Value = "Palestine" )]
    PS,

    /// <summary>
    /// PT, Portugal
    /// </summary>
    [EnumMember( Value = "Portugal" )]
    PT,

    /// <summary>
    /// PW, Palau
    /// </summary>
    [EnumMember( Value = "Palau" )]
    PW,

    /// <summary>
    /// PY, Paraguay
    /// </summary>
    [EnumMember( Value = "Paraguay" )]
    PY,

    /// <summary>
    /// QA, Qatar
    /// </summary>
    [EnumMember( Value = "Qatar" )]
    QA,

    /// <summary>
    /// RE, Réunion
    /// </summary>
    [EnumMember( Value = "Reunion" )]
    RE,

    /// <summary>
    /// RO, Romania
    /// </summary>
    [EnumMember( Value = "Romania" )]
    RO,

    /// <summary>
    /// RS, Serbia
    /// </summary>
    [EnumMember( Value = "Serbia" )]
    RS,

    /// <summary>
    /// RU, Russia
    /// </summary>
    [EnumMember( Value = "Russia" )]
    RU,

    /// <summary>
    /// RW, Rwanda
    /// </summary>
    [EnumMember( Value = "Rwanda" )]
    RW,

    /// <summary>
    /// SA, Saudi Arabia
    /// </summary>
    [EnumMember( Value = "Saudi Arabia" )]
    SA,

    /// <summary>
    /// SB, Solomon Islands
    /// </summary>
    [EnumMember( Value = "Solomon Islands" )]
    SB,

    /// <summary>
    /// SC, Seychelles
    /// </summary>
    [EnumMember( Value = "Seychelles" )]
    SC,

    /// <summary>
    /// SD, Sudan
    /// </summary>
    [EnumMember( Value = "Sudan" )]
    SD,

    /// <summary>
    /// SE, Sweden
    /// </summary>
    [EnumMember( Value = "Sweden" )]
    SE,

    /// <summary>
    /// SG, Singapore
    /// </summary>
    [EnumMember( Value = "Singapore" )]
    SG,

    /// <summary>
    /// SI, Slovenia
    /// </summary>
    [EnumMember( Value = "Slovenia" )]
    SI,

    /// <summary>
    /// SK, Slovakia
    /// </summary>
    [EnumMember( Value = "Slovakia" )]
    SK,

    /// <summary>
    /// SL, Sierra Leone
    /// </summary>
    [EnumMember( Value = "Sierra Leone" )]
    SL,

    /// <summary>
    /// SM, San Marino
    /// </summary>
    [EnumMember( Value = "San Marino" )]
    SM,

    /// <summary>
    /// SN, Senegal
    /// </summary>
    [EnumMember( Value = "Sénégal" )]
    SN,

    /// <summary>
    /// SO, Somalia
    /// </summary>
    [EnumMember( Value = "Somalia" )]
    SO,

    /// <summary>
    /// SR, Suriname
    /// </summary>
    [EnumMember( Value = "Suriname" )]
    SR,

    /// <summary>
    /// ST, São Tomé and Príncipe
    /// </summary>
    [EnumMember( Value = "São Tomé and Príncipe" )]
    ST,

    /// <summary>
    /// SV, El Salvador
    /// </summary>
    [EnumMember( Value = "El Salvador" )]
    SV,

    /// <summary>
    /// SY, Syria
    /// </summary>
    [EnumMember( Value = "Syria" )]
    SY,

    /// <summary>
    /// SZ, Eswatini
    /// </summary>
    [EnumMember( Value = "Swaziland" )]
    SZ,

    /// <summary>
    /// TC, Turks and Caicos Islands
    /// </summary>
    [EnumMember( Value = "Turks and Caicos Islands" )]
    TC,

    /// <summary>
    /// TD, Chad
    /// </summary>
    [EnumMember( Value = "Chad" )]
    TD,

    /// <summary>
    /// TG, Togo
    /// </summary>
    [EnumMember( Value = "Togo" )]
    TG,

    /// <summary>
    /// TH, Thailand
    /// </summary>
    [EnumMember( Value = "Thailand" )]
    TH,

    /// <summary>
    /// TJ, Tajikistan
    /// </summary>
    [EnumMember( Value = "Tajikistan" )]
    TJ,

    /// <summary>
    /// TL, Timor-Leste
    /// </summary>
    [EnumMember( Value = "Timor-Leste" )]
    TL,

    /// <summary>
    /// TM, Turkmenistan
    /// </summary>
    [EnumMember( Value = "Turkmenistan" )]
    TM,

    /// <summary>
    /// TN, Tunisia
    /// </summary>
    [EnumMember( Value = "Tunisia" )]
    TN,

    /// <summary>
    /// TO, Tonga
    /// </summary>
    [EnumMember( Value = "Togo" )]
    TO,

    /// <summary>
    /// TR, Turkey
    /// </summary>
    [EnumMember( Value = "Turkey" )]
    TR,

    /// <summary>
    /// TT, Trinidad and Tobago
    /// </summary>
    [EnumMember( Value = "Trinidad and Tobago" )]
    TT,

    /// <summary>
    /// TV, Tuvalu
    /// </summary>
    [EnumMember( Value = "Tuvalu" )]
    TV,

    /// <summary>
    /// TW, Taiwan
    /// </summary>
    [EnumMember( Value = "Taiwan" )]
    TW,

    /// <summary>
    /// TZ, Tanzania
    /// </summary>
    [EnumMember( Value = "Tanzania" )]
    TZ,

    /// <summary>
    /// UA, Ukraine
    /// </summary>
    [EnumMember( Value = "Ukraine" )]
    UA,

    /// <summary>
    /// UG, Uganda
    /// </summary>
    [EnumMember( Value = "Uganda" )]
    UG,

    /// <summary>
    /// US, United States
    /// </summary>
    [EnumMember( Value = "United States" )]
    US,

    /// <summary>
    /// UY, Uruguay
    /// </summary>
    [EnumMember( Value = "Uruguay" )]
    UY,

    /// <summary>
    /// UZ, Uzbekistan
    /// </summary>
    [EnumMember( Value = "Uzbekistan" )]
    UZ,

    /// <summary>
    /// VA, Vatican City
    /// </summary>
    [EnumMember( Value = "Vatican" )]
    VA,

    /// <summary>
    /// VC, Saint Vincent and the Grenadines
    /// </summary>
    [EnumMember( Value = "St. Vincent and the Grenadines" )]
    VC,

    /// <summary>
    /// VE, Venezuela
    /// </summary>
    [EnumMember( Value = "Venezuela" )]
    VE,

    /// <summary>
    /// VN, Vietnam
    /// </summary>
    [EnumMember( Value = "Vietnam" )]
    VN,

    /// <summary>
    /// VU, Vanuatu
    /// </summary>
    [EnumMember( Value = "Vanuatu" )]
    VU,

    /// <summary>
    /// WF, Wallis and Futuna
    /// </summary>
    [EnumMember( Value = "Wallis and Futuna Islands" )]
    WF,

    /// <summary>
    /// WS, Samoa
    /// </summary>
    [EnumMember( Value = "Western Samoa" )]
    WS,

    /// <summary>
    /// XK, Kosovo
    /// </summary>
    [EnumMember( Value = "Kosovo" )]
    XK,

    /// <summary>
    /// YE, Yemen
    /// </summary>
    [EnumMember( Value = "Yemen" )]
    YE,

    /// <summary>
    /// YT, Mayotte
    /// </summary>
    [EnumMember( Value = "Mayotte" )]
    YT,

    /// <summary>
    /// ZA, South Africa
    /// </summary>
    [EnumMember( Value = "South Africa" )]
    ZA,

    /// <summary>
    /// ZM, Zambia
    /// </summary>
    [EnumMember( Value = "Zambia" )]
    ZM,

    /// <summary>
    /// ZW, Zimbabwe
    /// </summary>
    [EnumMember( Value = "Zimbabwe" )]
    ZW,

}
