using InvoiceXpress.CountryGen;
using RestSharp;
using System.Text;


/*
 * ISO-3166 list of countries
 */
var api = new RestClient( "https://raw.githubusercontent.com/" ).UseJson();
var req = new RestRequest( "/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json" );

var resp = await api.GetAsync<List<Country>>( req );


/*
 * Load HTML fragment from InvoiceXpress website, which is
 * the drop-down with the list of countries.
 */
var html = await File.ReadAllLinesAsync( "opt.html" );
var iec = new List<string>();

foreach ( var l in html )
{
    if ( l.StartsWith( "<option value=" ) == false )
        continue;

    var ix = l.IndexOf( '"', 15 );
    var country = l.Substring( 15, ix - 15 );

    iec.Add( country );
}


/*
 * InvoiceXpress receives the country as a string! Since names
 * of countries (sometimes) change (or their value differs from
 * the official country name) we need a remap!
 */
var map = new Dictionary<string, string>();

// Not available in Invoice Express: 
map.Add( "AQ", "##skip" );  // AQ / Antarctica
map.Add( "AX", "##skip" );  // AX / Åland Islands

// Need remapping
//map.Add( "BA", "Bosnia-Herzegovina" );
//map.Add( "BN", "Brunei" );
//map.Add( "BO", "Bolivia" );
//map.Add( "CD", "Congo" );
//map.Add( "CV", "Cape Verde" );
//map.Add( "CZ", "Czech Republic" );
//map.Add( "FK", "Falkland Islands" );
//map.Add( "FO", "Faeroe Islands (Føroyar)" );
//map.Add( "GB", "UK" );
//map.Add( "KP", "Korea, North" );
//map.Add( "KR", "Korea, South" );
//map.Add( "LA", "Laos" );
//map.Add( "MD", "Moldova" );
//map.Add( "MF", "Martinique" );
//map.Add( "MK", "Macedonia (Former Yug. Rep.)" );
//map.Add( "IR", "Iran" );
//map.Add( "MO", "Macau" );
//map.Add( "PN", "Pitcairn Island" );
//map.Add( "PS", "Palestine" );
//map.Add( "RE", "Reunion" );
//map.Add( "RU", "Russia" );
//map.Add( "SN", "Sénégal" );
//map.Add( "ST", "São Tomé and Príncipe" );
//map.Add( "SY", "Syria" );
//map.Add( "SZ", "Swaziland" );
//map.Add( "TO", "Togo" );
//map.Add( "TW", "Taiwan" );
//map.Add( "TZ", "Tanzania" );
//map.Add( "US", "United States" );
//map.Add( "VA", "Vatican" );
//map.Add( "VE", "Venezuela" );
//map.Add( "VN", "Vietnam" );
//map.Add( "WS", "Western Samoa" );


/*
 * 
 */
var sb = new StringBuilder();

sb.AppendLine( @"// autogenerated
using InvoiceXpress.Json;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace InvoiceXpress;

/// <summary />
/// <remarks>
/// List of countries as per: https://invoicexpress.com/api-v2/documentation/appendix
/// </remarks>
[JsonConverter( typeof( EnumConverter ) )]
public enum Country
{
" );

var fg = Console.ForegroundColor;
var issueCount = 0;

foreach ( var country in resp!.OrderBy( x => x.Alpha2 ) )
{
    var ieName = country.Name;

    /*
     * Exceptions!
     */
    if ( map.ContainsKey( country.Alpha2 ) == true )
    {
        ieName = map[ country.Alpha2 ];

        if ( ieName == "##skip" )
            continue;
    }

    if ( iec.Contains( ieName ) == false && ieName.StartsWith( "Saint" ) == true )
        ieName = ieName.Replace( "Saint ", "St. " );

    if ( iec.Contains( ieName ) == false )
    {
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.WriteLine( "warn: issue with country {0} / {1}", country.Alpha2, country.Name );
        Console.ForegroundColor = fg;

        issueCount++;
        continue;
    }


    sb.AppendLine( $"    /// <summary>" );
    sb.AppendLine( $"    /// { country.Alpha2 }, { country.Name }" );
    sb.AppendLine( $"    /// </summary>" );
    sb.AppendLine( $"    [EnumMember( Value = \"{ ieName }\" )]" );
    sb.AppendLine( $"    { country.Alpha2 }," );
    sb.AppendLine();
}

sb.AppendLine( "}" );


/*
 * 
 */
if ( issueCount > 0 )
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine( "err: {0} issues with country mapping", issueCount );
    Console.ForegroundColor = fg;

    return 1;
}


if ( args.Length == 0 )
{
    Console.WriteLine( sb.ToString() );
}
else
{
    await File.WriteAllTextAsync( args[ 0 ], sb.ToString() );
}

return 0;

/* eof */
